### ISSUE TITLE
Properly setup GitHub Oauth

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced#146]
## Do you want to request a *feature* or report a *bug*?
feature/bug
## What is the current behavior?
At the moment GitHub Login does not. I am looking into creating an Oauth App to handle the authentication
 
### If the current behavior is a bug, please provide the steps to reproduce.
Open the home page and see login is broken

![Screenshot 2019-08-30 09 47 23](https://user-images.githubusercontent.com/5713670/64037781-586b0c00-cb0b-11e9-88af-4d8b9a575949.png)

## What is the expected behavior?

I expect the login to work. Looking into to using one of the following solutions. 

https://www.onegraph.com/docs/logging_users_in_and_out.html

or

https://github.com/checkr/react-github-login

**Comment by bdougie** [comment]
heads up @sgrove I will probably put some time into this, this weekend.

**Comment by sgrove** [comment]
I just about had it last night, just need to make it reactive through the
whole app!

**Comment by bdougie** [comment]
solved with #149
