### ISSUE TITLE
Content is not centered

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced#303]
<img width="1659" alt="Screenshot 2019-10-15 13 13 20" src="https://user-images.githubusercontent.com/5713670/66853583-9e5e2100-ef4d-11e9-9d88-14c9acd4d8fa.png">

**Comment by nersoh** [comment]
I'll try to fix this one. 😉

**Comment by nersoh** [comment]
Ops. There is already a PR for that #304
