### ISSUE TITLE
GitHub authentication

### ISSUE THREAD

**Issue by rolfea** [bdougie/open-sauced#31]
**- Do you want to request a *feature* or report a *bug*?**
**Feature**  
Given that this project circulates around GitHub projects, I think that a user should be able to authenticate and sign in with their GitHub account.  
  
My understanding currently is that each user has their own version of Open Sauced hosted on something like Netlify, but there isn't anything in place to prevent someone else from adding repositories or comments to another user's list.  
Adding GitHub authentication would protect users from potential vandalism or accidental editing of OpenSauce lists and also could open the doors to other interesting integrations with GitHub's API, such as grabbing 'starred' repos, etc.

**Comment by bdougie** [comment]
I am going to take a crack at this, this weekend.

**Comment by bdougie** [comment]
I am going to leverage one of Netlify's new features for this. [Identity](https://www.netlify.com/blog/2017/09/07/introducing-built-in-identity-service-to-streamline-user-management/)

**Comment by bdougie** [comment]
Closing for now since Netlify Identity does not offer GitHub login by itself, email is the default. I am looking to add the git-gateway instead to leverage GitHub features and tokens
