### ISSUE TITLE
When creating data changes, no components are re-rendering.

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced#348]
Context:

https://github.com/bdougie/open-sauced/issues/255 & https://github.com/bdougie/open-sauced/issues/215 are both instances where data changes on triggering a Mutation. Not that we are fully using hooks, the error is gone. The problem of the data not updating when the mutation finishes now exist. 

Things to fix:

- [x] As a user I should create a new goal and see it populate in the list without refreshing the page
- [ ] As a user without any open-sauced-data, I should be able to click a "create a goal" button and be presented with a blank repo list without refreshing the page..

**Comment by bdougie** [comment]
Labeling as a bug, because it should get addressed sooner than later.

**Comment by bdougie** [comment]
@NileshPatel17 do you have any thoughts on this? Or have experience with data stores outside of redux? 

I am looking into leveraging [this pattern with Apollo caching](https://spin.atomicobject.com/2019/11/05/simplifying-apollo-client-local-cache/) and useReducer..

**Comment by bdougie** [comment]
Actually, I think the solution is leveraging apollo better with the [@apollo/react-hooks](https://www.apollographql.com/docs/react/data/queries/).

```js
import gql from 'graphql-tag';
import { useQuery } from '@apollo/react-hooks';

const GET_DOGS = gql`
  {
    dogs {
      id
      breed
    }
  }
`;

function Dogs({ onDogSelected }) {
  const { loading, error, data } = useQuery(GET_DOGS);

  if (loading) return 'Loading...';
  if (error) return `Error! ${error.message}`;

  return (
    <select name="dog" onChange={onDogSelected}>
      {data.dogs.map(dog => (
        <option key={dog.id} value={dog.breed}>
          {dog.breed}
        </option>
      ))}
    </select>
  );
}
```

In addition to that also add localState management with apollo/react-hooks. I might use this as a guide: [Learn how to work with your local data in Apollo Client
](https://www.apollographql.com/docs/react/data/local-state/)

> ## Updating local state
>There are two main ways to perform local state mutations. The first way is to directly write to the cache by calling cache.writeData. Direct writes are great for one-off mutations that don't depend on the data that's currently in the cache, such as writing a single value. The second way is by leveraging the useMutation hook with a GraphQL mutation that calls a local client-side resolver. We recommend using resolvers if your mutation depends on existing values in the cache, such as adding an item to a list or toggling a boolean.

**Comment by NileshPatel17** [comment]
let me explore apollo-cache-inmemory

**Comment by bdougie** [comment]
I tried this a little last night and did the initial setup. From my exploration a custom hook may be needed to take the OneGraph implementation into account. I could not quite figure it out on first pass and ran out of time. 

I have not created a custom hook before and using [this article on local caching](https://spin.atomicobject.com/2019/11/05/simplifying-apollo-client-local-cache/) as inspiration. Let me know if you get farther in your discovery @NileshPatel17

**Comment by NileshPatel17** [comment]
> * As a user I should create a new goal and see it populate in the list without refreshing the page

This issue has been taken care in #383 

** Yet to explore ```apollo-cache-inmemory```

**Comment by NileshPatel17** [comment]
is it possible to deploy code from PR having in draft state??

**Comment by NileshPatel17** [comment]
alright. it is possible. It is deployed at ```https://deploy-preview-383--open-sauced.netlify.com/```
let me know what do you think.

**Comment by bdougie** [comment]
> ** Yet to explore apollo-cache-inmemory

@NileshPatel17 I left comments on the PR. Regarding the caching, it doesn't have to be addressed in your current PR since it is actually unrelated to this issue. It is related to #262, I made the original suggestion on the wrong issue to begin with. 

Thanks for PR, it is very much appreciated.
