### ISSUE TITLE
Add repo form is allows https, but stores it as undefined

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced#354]
When a user adds a repo using the full URL, it works but it saves the name as `undefined`.

The expectation is that undefined should be saved. Perha

Steps to fix:
- [ ] write a test that ensures that only the save data can only be the `owner/repo` format.
- [ ] add a sanitizer to properly remove the `https://github.com/`

Line that should be fixed is: https://github.com/bdougie/open-sauced/blob/master/src/components/AddRepoForm.js#L20

**Comment by bdougie** [comment]
![Screenshot 2019-11-06 06 00 20](https://user-images.githubusercontent.com/5713670/68308539-deeb1f00-0061-11ea-8437-8054214fd4ec.png)

**Comment by NileshPatel17** [comment]
PR #357 created
