### ISSUE TITLE
Creating an open-sauced-goals repo should default as private

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced#355]
Now that I am using this project today, I personally feel as if my notes should be private by default and maintainers should not be able to read my thoughts on their projects. 

Line to changed:
https://github.com/bdougie/open-sauced/blob/master/src/lib/apiGraphQL.js#L198

To clarify is should be `PRIVATE` and not `PUBLIC`

**Comment by bdougie** [comment]
If you work on this, keep in mind that this bug #348 will require you to hard refresh the page when creating a goals repo in UI.

**Comment by NileshPatel17** [comment]
created PR #356
