### ISSUE TITLE
Add version number to console

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced#390]
To assist with debugging it would be nice console.log the version number of the site. The [package.json](https://github.com/bdougie/open-sauced/blob/master/package.json#L3) has the version number, but it would be nice to print that version to the console 

An [example of how to do this from stackoverflow](https://stackoverflow.com/questions/9153571/is-there-a-way-to-get-version-from-package-json-in-nodejs-code).

My suggestion would is placing this in the [lib](https://github.com/bdougie/open-sauced/tree/master/src/lib) folder and importing into the [App.js](https://github.com/bdougie/open-sauced/tree/master/src/containers)

```js
const packageJson = path.dirname(require.resolve('package-name')) + '/package.json';
const { version } = require(packageJson);
console.log('version', version)
```

**Comment by jafaryfarzaneh** [comment]
I'm working on it.

**Comment by bdougie** [comment]
Excellent! Thanks so much

**Comment by bdougie** [comment]
Thanks @jafaryfarzaneh
