### ISSUE TITLE
Bug: Notes box does not have a cancel button and only a delete

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced#469]
![CEC5181C-2EF9-4983-9C0E-4CAA7EEB2823](https://user-images.githubusercontent.com/5713670/73606209-5e788380-45a8-11ea-9504-a3bada12cab1.png)

I notice while saving a note there was no cancel button. Considering I built and made the design for this, I know that the pictured delete button should say “Cancel” and not delete.

**Comment by tonymuu** [comment]
Hey Brian, the project looks fun. Could I go ahead and take on this issue?

**Comment by bdougie** [comment]
Please, that would be appreciated @tonymuu

**Comment by bdougie** [comment]
@tonymuu checking in to see if you had questions or still interested in approaching this problem.

**Comment by bdougie** [comment]
Specifically for anyone who would like to contribute. This is adding a cancel button above here https://github.com/bdougie/open-sauced/blob/master/src/components/NoteForm.js#L72-L75. You can use the same `editing` boolean as well.

**Comment by yg** [comment]
I'm taking this @bdougie
