### ISSUE TITLE
Ability to close banner on top

### ISSUE THREAD

**Issue by yg** [bdougie/open-sauced#527]
![Screenshot](https://user-images.githubusercontent.com/61746440/82110156-a8513800-9759-11ea-8173-2cd50adea9ec.png)

**Comment by bdougie** [comment]
Curious to learn more about this thought. My thought is that the context card at the top will give you info on what is below. Admittedly they provide a ton of information at the moment or event a good amount of context.

**Comment by yg** [comment]
It would be great if we change the way of displaying the context as **npmjs** do.

**Comment by bdougie** [comment]
So like this?

![Screenshot 2020-05-28 06 29 44](https://user-images.githubusercontent.com/5713670/83147539-aa49be00-a0ac-11ea-9169-76afd9c5b661.png)
