### ISSUE TITLE
Authentication not working on local instance

### ISSUE THREAD

**Issue by yg** [bdougie/open-sauced#529]
Authentication not working on local instance

1. Created Opengraph account
2. Created an App
3. Pasted my app ID in `src/config.js`
4. Added my domain to CORS

While clicking Login with GitHub it stays in the same page!

Here is my GraphQL Response

```json
{"data":{"me":{"serviceMetadata":{"loggedInServices":[{"service":"GITHUB","foreignUserId":null}]}}}}
```

Help me sort out this issue @bdougie so I can work on #528

**Comment by bdougie** [comment]
You shouldn't need a monograph account to work on this locally. The auth should point to production data. Are you able to provide more details the steps taken to get this working locally.

My workflow is:

1. git clone this repo
2. npm install && npm start

I realize I am the sole contributor at the moment, so it is possible I missed a step.

---
Happy to set up a pair session where we could sync on this.

**Comment by yg** [comment]
@bdougie Yay :tada:, It works on localhost.
