### ISSUE TITLE
Better navbar design

### ISSUE THREAD

**Issue by yg** [bdougie/open-sauced#540]
### Is your feature request related to a problem? Please describe.

Currently, the navbar seems little flat

### Describe the solution you'd like

We can design a navbar which is more accessible in terms of functionality and design

### Describe alternatives you've considered

- GitHub's Navbar
- Twitter's Old Navbar

If ok, I'm ready to work on this!

**Comment by bdougie** [comment]
Happy to see examples. Https://primer.style have components for a GitHub type nav

**Comment by yg** [comment]
Yes primer is cool!

**Comment by yg** [comment]
.take
