### ISSUE TITLE
Finish Homepage implementation.

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced#545]
### Describe the solution you'd like

The homepage needs to more components implemented. Each component should be represented in a storybook and reuse components where possible. There is probably an opportunity for code clean up or reorganization of components, which is fine to do as long as it doesn't detract from the home page work.

- [ ] Hero (exists but not completed)
- [ ] Login box
- [ ] Description
- [ ] Quote box(orange boxes should be avatars)
- [ ] More details box
- [ ] updated footer.

### Describe alternatives you've considered

The "Trusted by section" is meant for projects I hope to reach out to. For now, we can list the following projects. 

- mutualfun
- bdougie
- Hackathon
- CodeNaija

For the quotes section we can just use lorem ipsum for now. When the site is stage I can reach out to projects and people for quotes. It will be easier to get that when they have something to look at. 

### Additional context
I worked on the initial implement which is what you see in #502 

[Link to design details and assets](https://zpl.io/VKg1WwP)

![](https://user-images.githubusercontent.com/5713670/79365150-160e0800-7eff-11ea-9fc3-4ec55ea7771b.png)

cc/ @yg since some of your work on the navbar has overlapped with this. Your feedback is welcomed.

**Comment by yg** [comment]
@bdougie Wow, this really really awesome! :heart_eyes: 

![](https://media3.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy-downsized-medium.gif)

Can we merge the navbar PR first if okay and then we start working on this! So we can prevent merge conflicts!

**Comment by yg** [comment]
@bdougie Can you invite me to this project https://zpl.io/VKg1WwP

me@yogi.codes
