### ISSUE TITLE
Contact page with netlify forms

### ISSUE THREAD

**Issue by yg** [bdougie/open-sauced#547]
### Describe the solution you'd like

It would be great if we have **contact us** page with **netlify forms** https://docs.netlify.com/forms/setup/

![](https://media1.giphy.com/media/ZBVRlQamUaAMAOWDHB/giphy.gif)

**Comment by bdougie** [comment]
I'd prefer the contact to happen through GitHub Discussions or Issues instead. By the nature of the project being open source, it would lend itself to having conversations in the open and not on another platform.

I can reach out @becca to request this repo to get access.

**Comment by becca** [comment]
@bdougie you should have access now to enable for this repository

**Comment by bdougie** [comment]
Thanks @becca!

**Comment by bdougie** [comment]
@yg I am going to set up some design discussions this afternoon.

**Comment by yg** [comment]
Thanks @becca!
