### ISSUE TITLE
New buttons

### ISSUE THREAD

**Issue by yg** [bdougie/open-sauced#548]
### Describe the solution you'd like

It would be great if we have a new button design, currently, the buttons are huge and weird hover colors.

![Screenshot](https://user-images.githubusercontent.com/61746440/82811468-799c3580-9eae-11ea-8ad9-e6550c825176.png)

### Describe alternatives you've considered

GitHub Primer Styles
Dev.to
Tailwind CSS Buttons

**Comment by bdougie** [comment]
Happy to explore this. Feel free to post screenshots for examples as well.

**Comment by yg** [comment]
@bdougie In this blog, we can find huge list of buttons design!

https://dev.to/webdeasy/top-20-css-buttons-animations-f41
