### ISSUE TITLE
It would be great if we remove underlines for links

### ISSUE THREAD

**Issue by yg** [bdougie/open-sauced#549]
### Describe the solution you'd like

It would be great if we remove underlines for links

### Describe alternatives you've considered

GitHub Issues / PRs List

**Comment by bdougie** [comment]
The Typography folder has reusable components for links. The accent or subtle links may work as a quick update. 

https://github.com/bdougie/open-sauced/tree/master/src/styles/Typography

**Comment by Brawrdon** [comment]
I think it would be best to keep links underlined, but only when they're not in a list or navigation, for the sake of accessbility.

See: [https://www.nngroup.com/articles/guidelines-for-visualizing-links/](Jakob Nielsen's post on link affordances)

(What I'm suggesting seems to already be in place, but seeing the site on @bdougie's stream seems to show underlines on the issue lists... Maybe there's a different version or I'm going crazy 😅🤔)
