### ISSUE TITLE
Repo metadata in header card

### ISSUE THREAD

**Issue by yg** [bdougie/open-sauced#551]
### Describe the solution you'd like

We can show repo metadata in the header card of Repository page.

Metadata Like

- Description
- Website
- Number of commits
- Number of branches
- Number of releases
- Number of contributors
- License used
- Repo topics

### Additional context

We find huge whitespace in a header card we can will with the above-listed metadata!

![Screenshot](https://user-images.githubusercontent.com/61746440/82812117-e532d280-9eaf-11ea-9169-6d17e0859fc4.png)

**Comment by bdougie** [comment]
I like this idea. The existing repo metadata lives in the sidebar, but that content also has a lot of space. Combining that content into the same card would make better use of space.

![Screenshot 2020-05-25 07 49 21](https://user-images.githubusercontent.com/5713670/82823416-606a9900-9e5c-11ea-89b0-f45e726e990d.png)

**Comment by yg** [comment]
.take
