### ISSUE TITLE
Add a discord message action to announce when a new release has been cut.

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced#553]
### Describe the solution you'd like

From a quick search this exist: https://github.com/marketplace/actions/actions-for-discord.

Using something similar a message can be sent to the discord channel when a release has been cut. 

### Describe alternatives you've considered

Use the `on: release`.

### Additional context

[Link to discord](https://discord.gg/nMkZde)

**Comment by bdougie** [comment]
testing the webhook

**Comment by yg** [comment]
Test

**Comment by bdougie** [comment]
For now, we can just use the general discord webhook.
