### ISSUE TITLE
Return key should add a new repo

### ISSUE THREAD

**Issue by Brawrdon** [bdougie/open-sauced#554]
### Is your feature request related to a problem? Please describe.

When adding a repository, you **have** to click the add button. This is annoying especially when trying to quickly set up the dashboard but could also be an accessiblity issue.

### Describe the solution you'd like

Presing the return key should add a repo.

**Comment by bdougie** [comment]
I would also love this feature. Make the return button work!

**Comment by bdougie** [comment]
Fixed in #557
